-- Run this in the Supabase SQL Editor.
-- It creates the tables, RLS policies, storage policies, and seed categories
-- expected by the current frontend.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  name text not null,
  avatar_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.subcategories (
  id bigint primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (category_id, name)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  subcategory_id bigint references public.subcategories(id) on delete set null,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null,
  image_path text,
  image text generated always as (image_path) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create index if not exists idx_subcategories_category_id
  on public.subcategories (category_id);

create index if not exists idx_products_category_id
  on public.products (category_id);

create index if not exists idx_products_subcategory_id
  on public.products (subcategory_id);

create index if not exists idx_cart_items_user_id
  on public.cart_items (user_id);

create index if not exists idx_cart_items_product_id
  on public.cart_items (product_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_cart_items_updated_at on public.cart_items;
create trigger set_cart_items_updated_at
before update on public.cart_items
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1), 'User')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    name = excluded.name;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.products enable row level security;
alter table public.cart_items enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "categories_public_read" on public.categories;
create policy "categories_public_read"
on public.categories
for select
to anon, authenticated
using (true);

drop policy if exists "subcategories_public_read" on public.subcategories;
create policy "subcategories_public_read"
on public.subcategories
for select
to anon, authenticated
using (true);

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "cart_items_select_own" on public.cart_items;
create policy "cart_items_select_own"
on public.cart_items
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "cart_items_insert_own" on public.cart_items;
create policy "cart_items_insert_own"
on public.cart_items
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "cart_items_update_own" on public.cart_items;
create policy "cart_items_update_own"
on public.cart_items
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "cart_items_delete_own" on public.cart_items;
create policy "cart_items_delete_own"
on public.cart_items
for delete
to authenticated
using (auth.uid() = user_id);

insert into public.categories (id, name) values
  (1, 'Women''s Fashion'),
  (2, 'Men''s Fashion'),
  (37, 'Kid''s & Baby'),
  (38, 'Beauty & Care'),
  (39, 'Home Essentials'),
  (40, 'Furniture'),
  (41, 'Toys & Games'),
  (42, 'Arts & crafts')
on conflict (id) do update
set name = excluded.name;

insert into public.subcategories (id, category_id, name) values
  (13, 1, 'Dresses'),
  (14, 1, 'Tops'),
  (15, 1, 'Bottoms'),
  (16, 1, 'Shoes/Heels'),
  (17, 1, 'Accessories'),
  (18, 2, 'Accessories'),
  (19, 2, 'Shirt'),
  (20, 2, 'Pants'),
  (21, 2, 'Shoes'),
  (22, 2, 'Suits'),
  (23, 37, 'Girls'),
  (24, 37, 'Boys'),
  (25, 37, 'Babys'),
  (26, 37, 'Toys'),
  (27, 38, 'Skin care'),
  (28, 38, 'Hair care'),
  (29, 38, 'Body care'),
  (30, 38, 'Fragrance'),
  (31, 38, 'Makeup'),
  (32, 39, 'Kitchen'),
  (33, 39, 'Bathroom'),
  (34, 39, 'Cleaning'),
  (35, 39, 'Storage'),
  (36, 39, 'Decor'),
  (37, 40, 'Living Room'),
  (38, 40, 'Bedroom'),
  (39, 40, 'Dining'),
  (40, 40, 'Office'),
  (41, 40, 'Outdoors'),
  (42, 41, 'Educational'),
  (43, 41, 'Action figures'),
  (44, 41, 'Bored games'),
  (45, 41, 'Electronics'),
  (46, 41, 'Outdoor'),
  (47, 42, 'Supllies'),
  (48, 42, 'DIY kits'),
  (49, 42, 'painting'),
  (50, 42, 'Scrapbooking')
on conflict (id) do update
set
  category_id = excluded.category_id,
  name = excluded.name;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update
set public = true;

drop policy if exists "product_images_public_read" on storage.objects;
create policy "product_images_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "product_images_authenticated_upload" on storage.objects;
create policy "product_images_authenticated_upload"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "product_images_authenticated_update" on storage.objects;
create policy "product_images_authenticated_update"
on storage.objects
for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "product_images_authenticated_delete" on storage.objects;
create policy "product_images_authenticated_delete"
on storage.objects
for delete
to authenticated
using (bucket_id = 'product-images');
